mcpartv = 'std::vector<simb::MCParticle>'
mctruthv = 'std::vector<simb::MCTruth>'
edepv = 'std::vector<sim::SimEnergyDeposit>'
simphotv = 'std::vector<sim::SimPhotonsLite>'
digitv = 'std::vector<raw::RawDigit>'
wirev = 'std::vector<recob::Wire>'
beamv = 'std::vector<beam::ProtoDUNEBeamEvent>'
trackv = 'std::vector<recob::Track>'
showerv = 'std::vector<recob::Shower>'
calov = 'std::vector<anab::Calorimetry>'
tsv = 'std::vector<raw::RDTimeStamp>'


ophitv = 'std::vector<recob::OpHit>'
opdetwfv = 'std::vector<raw::OpDetWaveform>'
opwfv = 'std::vector<recob::OpWaveform>'
opflashv = 'std::vector<recob::OpFlash>'