#!/bin/bash
#
# Emit a wrapper fcl pairing one reco (stage-2) file with its raw (stage-1)
# file for the ProtoDUNE-HD signal-to-noise job.
#
# art has no command-line option for secondary input files -- they can only be
# set in FHiCL -- and the secondaryFileNames "a" key must be byte-identical to
# the source.fileNames entry it refers to. Passing the primary with `lar -s`
# instead replaces source.fileNames, the key stops matching, and art silently
# supplies no secondaries. Generating both from the same shell variable makes
# the match hold by construction.
#
# The TFileService output name is derived from the primary file's basename, so
# that many grid jobs writing into the same directory do not all produce
# pdhd_signaltonoise.root and clobber one another.
#
# Usage:
#   make_sn_fcl.sh <primary_reco_file> <secondary_raw_file> [output.fcl]
#
#   PRIMARY=root://.../..._reco_stage1_reco_stage2_..._keepup.root
#   SECONDARY=root://.../..._reco_stage1.root
#   make_sn_fcl.sh "$PRIMARY" "$SECONDARY" job.fcl
#   lar -c job.fcl          # note: no -j, secondary files are single-threaded only
#

set -euo pipefail

if [ $# -lt 2 ] || [ $# -gt 3 ]; then
  echo "usage: $(basename "$0") <primary_reco_file> <secondary_raw_file> [output.fcl]" >&2
  exit 1
fi

PRIMARY="$1"
SECONDARY="$2"
OUT="${3:-pdhd_signaltonoise_job.fcl}"

if [ "$PRIMARY" = "$SECONDARY" ]; then
  echo "error: primary and secondary are the same file" >&2
  exit 1
fi

# A bare local path works, but only if it is spelled the same way in both
# places; normalise it here so a relative argument cannot desync the two.
case "$PRIMARY" in
  *://*) ;;
  *) PRIMARY="$(readlink -f "$PRIMARY")" ;;
esac
case "$SECONDARY" in
  *://*) ;;
  *) SECONDARY="$(readlink -f "$SECONDARY")" ;;
esac

# Distinct output name per input, so parallel jobs do not collide.
TFNAME="sn_$(basename "$PRIMARY" .root).root"

cat > "$OUT" <<EOF
#
# Generated by make_sn_fcl.sh on $(date -u +%Y-%m-%dT%H:%M:%SZ)
#
# primary   (reco, stage2): $PRIMARY
# secondary (raw,  stage1): $SECONDARY
#
# Run single-threaded: do NOT pass -j. Do not override source.fileNames with
# -s, or the secondaryFileNames key below will stop matching.
#

#include "pdhd_signaltonoise.fcl"

source.fileNames: [ "$PRIMARY" ]

source.secondaryFileNames: [
  {
    a: "$PRIMARY"
    b: [ "$SECONDARY" ]
  }
]

services.TFileService.fileName: "$TFNAME"
EOF

echo "wrote $OUT"
echo "  primary   $PRIMARY"
echo "  secondary $SECONDARY"
echo "  output    $TFNAME"
echo "run with:  lar -c $OUT"
